# -*- coding: utf-8 -*-
"""predict

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NDFrY5d4WA8W1urn8j1pTWKifYcGVH0D
"""

import torch
import torch.nn.functional as F
from transformers import AutoTokenizer, AutoModelForSequenceClassification

MODEL_PATH = "Mazen-Ghazy/bert-imdb-sentiment"
tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH)
model = AutoModelForSequenceClassification.from_pretrained(MODEL_PATH)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
model.eval()

def predict_sentiment(text):
    inputs = tokenizer(text,return_tensors="pt",truncation=True,padding=True,max_length=256)
    inputs = {key: value.to(device) for key, value in inputs.items()}
    with torch.no_grad():
        outputs = model(**inputs)
    probabilities = F.softmax(outputs.logits, dim=1)
    prediction = torch.argmax(probabilities, dim=1).item()
    confidence = probabilities[0][prediction].item() * 100
    sentiment = "Positive" if prediction == 1 else "Negative"
    return sentiment, confidence

    if __name__ == "__main__":
      print("=" * 50)
      print("IMDb Sentiment Analysis using BERT")
      print("=" * 50)
      while True:
         review = input("\nEnter a review (or type 'exit' to quit): ")
         if review.lower() == "exit":
            print("\nGoodbye!")
            break
         sentiment, confidence = predict_sentiment(review)
         print("-" * 50)
         print(f"Review     : {review}")
         print(f"Prediction : {sentiment}")
         print(f"Confidence : {confidence:.2f}%")
         print("-" * 50)

